LangString addOrReinstall ${LANG_CZECH} "Přidat nebo znovu nainstalovat součásti"
LangString alreadyInstalled ${LANG_CZECH} "Aplikace je již nainstalovaná"
LangString alreadyInstalledLong ${LANG_CZECH} "${PRODUCTNAME} ${VERSION} je již nainstalován. Vyberte další postup a pokračujte tlačítkem Další."
LangString appRunning ${LANG_CZECH} "${PRODUCTNAME} je spuštěn. Zavřete aplikaci a zkuste to znovu."
LangString appRunningOkKill ${LANG_CZECH} "${PRODUCTNAME} je spuštěn.$\nTlačítko OK aplikaci ukončí."
LangString chooseMaintenanceOption ${LANG_CZECH} "Vyberte požadovanou operaci."
LangString choowHowToInstall ${LANG_CZECH} "Vyberte způsob instalace ${PRODUCTNAME}."
LangString createDesktop ${LANG_CZECH} "Vytvořit zástupce na ploše"
LangString dontUninstall ${LANG_CZECH} "Ponechat stávající instalaci"
LangString dontUninstallDowngrade ${LANG_CZECH} "Ponechat stávající instalaci (přechod na starší verzi vyžaduje odinstalaci)"
LangString failedToKillApp ${LANG_CZECH} "Aplikaci ${PRODUCTNAME} se nepodařilo ukončit. Zavřete ji a zkuste to znovu."
LangString installingWebview2 ${LANG_CZECH} "Instaluje se WebView2..."
LangString newerVersionInstalled ${LANG_CZECH} "Je nainstalována novější verze ${PRODUCTNAME}. Před instalací starší verze doporučujeme současnou verzi odinstalovat. Vyberte další postup a pokračujte tlačítkem Další."
LangString older ${LANG_CZECH} "starší"
LangString olderOrUnknownVersionInstalled ${LANG_CZECH} "Je nainstalována starší nebo neznámá verze ${PRODUCTNAME}. Vyberte další postup a pokračujte tlačítkem Další."
LangString silentDowngrades ${LANG_CZECH} "Tento instalátor nepovoluje tichý přechod na starší verzi. Použijte grafický instalátor.$\n"
LangString unableToUninstall ${LANG_CZECH} "Odinstalace se nezdařila."
LangString uninstallApp ${LANG_CZECH} "Odinstalovat ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CZECH} "Před instalací odinstalovat současnou verzi"
LangString unknown ${LANG_CZECH} "neznámá"
LangString webview2AbortError ${LANG_CZECH} "Instalace WebView2 selhala. Aplikace bez něj nemůže běžet. Spusťte instalátor znovu."
LangString webview2DownloadError ${LANG_CZECH} "Stahování WebView2 selhalo: $0"
LangString webview2DownloadSuccess ${LANG_CZECH} "Instalační program WebView2 byl stažen."
LangString webview2Downloading ${LANG_CZECH} "Stahuje se instalační program WebView2..."
LangString webview2InstallError ${LANG_CZECH} "Instalace WebView2 selhala s kódem $1."
LangString webview2InstallSuccess ${LANG_CZECH} "WebView2 byl nainstalován."
LangString deleteAppData ${LANG_CZECH} "Odstranit místní data aplikace"
